version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: wonga_postgres
    environment:
      POSTGRES_USER: wonga
      POSTGRES_PASSWORD: wonga123
      POSTGRES_DB: wonga_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/Wonga.Api
    container_name: wonga_api
    ports:
      - "5030:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=wonga_db;Username=wonga;Password=wonga123
      - Jwt__Key=SUPER_SECRET_DEVELOPMENT_KEY_12345
      - Jwt__Issuer=WongaApi
      - Jwt__Audience=WongaClient
    depends_on:
      - postgres
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: wonga_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wonga.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

